name: NuGet Auth and Restore
description: Authenticate to GitHub Packages and restore NuGet dependencies.
inputs:
  working-directory:
    description: Directory to run restore in.
    required: true

runs:
  using: composite
  steps:
    - name: Set credentials for GitHub source
      shell: bash
      run: |
        dotnet nuget update source github \
          --username "${{ github.repository_owner }}" \
          --password "${{ secrets.GITHUB_TOKEN }}" \
          --store-password-in-clear-text \
          --configfile "${{ github.workspace }}/nuget.prod.config"

    - name: Restore dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dotnet restore --configfile "${{ github.workspace }}/nuget.prod.config"
