using './main.bicep'

param projectName = 'int'
param integrationName = toLower('GoogleDrive')
param sharedAppServicePlanName = 'asp-int-shared'
param sharedStorageAccountName = 'stintsharedg7lv'
param sharedKeyVaultName = 'kv-int-shared-k4h7'
param driveWorkJsonCredentialsSecretName = 'GoogleDrive-DriveWorkJsonCredentials'
param drivePersonalJsonCredentialsSecretName = 'GoogleDrive-DrivePersonalJsonCredentials'
param googleApplicationName = 'Integration Platform'
param concurrentDownloads = 100
param accountingDocumentationExportFolderId = '1k6XMCP0xjcy67bgEV6zAdxEUrdjm68Hv'
param accountingDocumentationBackupFolderId = '1f8zXjg9VY-cJj1q6JYtuyyhrLJENhrhs'
param accountingDocumentationBackupFileNamePrefix = 'accounting-documentation-'
param accountingDocumentationBackupCronSchedule = '0 0 2 1 * *'
param henrySavesExportFolderId = '1LkvQhmCxBkqbwWbRSV-y8NWKpiyfxuHV'
param henrySavesBackupFolderId = '1FF31ffaKn9RZQx4D7qFI-jgrccdEfRLT'
param henrySavesBackupFileNamePrefix = 'henry-saves-'
param henrySavesBackupCronSchedule = '0 0 2 */7 * *'
param timeZone = 'Central European Standard Time'
