using './main.bicep'

param projectName = 'int'
param integrationName = toLower('GoogleDrive')
param sharedAppServicePlanName = 'asp-int-shared'
param sharedStorageAccountName = 'stintsharedg7lv'
param sharedKeyVaultName = 'kv-int-shared-k4h7'
param driveWorkJsonCredentialsSecretName = 'GoogleDrive-DriveWorkJsonCredentials'
param drivePersonalJsonCredentialsSecretName = 'GoogleDrive-DrivePersonalJsonCredentials'
param googleApplicationName = 'Integration Platform'
param concurrentDownloads = 100
param accountingDocumentationDriveFolderId = '1k6XMCP0xjcy67bgEV6zAdxEUrdjm68Hv'
param accountingDocumentationBackupContainerName = 'accounting-documentation-backups'
param accountingDocumentationBackupFileNamePrefix = 'accounting-documentation-'
param accountingDocumentationBackupCronSchedule = '0 0 2 1 * *'
param henrySavesDriveFolderId = '1LkvQhmCxBkqbwWbRSV-y8NWKpiyfxuHV'
param henrySavesBackupContainerName = 'henry-saves-backups'
param henrySavesBackupFileNamePrefix = 'henry-saves-'
param henrySavesBackupCronSchedule = '0 15 2 1 * *'
param timeZone = 'Central European Standard Time'
